import { Country } from './country';

export const countries: Country[] = [
  { id: 1, countryCode: 'AF', countryName: `Afghanistan`, countryDialCode: `+93` },
  { id: 2, countryCode: 'ZA', countryName: `Afrique du Sud`, countryDialCode: `+27` },
  { id: 3, countryCode: 'AL', countryName: `Albanie`, countryDialCode: `+355` },
  { id: 4, countryCode: 'DZ', countryName: `Algérie`, countryDialCode: `+213` },
  { id: 5, countryCode: 'DE', countryName: `Allemagne`, countryDialCode: `+49` },
  { id: 6, countryCode: 'AD', countryName: `Andorre`, countryDialCode: `+376` },
  { id: 7, countryCode: 'AO', countryName: `Angola`, countryDialCode: `+244` },
  { id: 8, countryCode: 'AI', countryName: `Anguilla`, countryDialCode: `+1264` },
  { id: 9, countryCode: 'AQ', countryName: `Antarctique`, countryDialCode: `+672` },
  { id: 10, countryCode: 'AG', countryName: `Antigua-et-Barbuda`, countryDialCode: `+1268` },
  { id: 11, countryCode: 'AN', countryName: `Antarctique`, countryDialCode: `+672` },
  { id: 12, countryCode: 'SA', countryName: `Arabie saoudite`, countryDialCode: `+966` },
  { id: 13, countryCode: 'AR', countryName: `Argentine`, countryDialCode: `+54` },
  { id: 14, countryCode: 'AM', countryName: `Arménie`, countryDialCode: `+374` },
  { id: 15, countryCode: 'AW', countryName: `Aruba`, countryDialCode: `+297` },
  { id: 16, countryCode: 'AU', countryName: `Australie`, countryDialCode: `+61` },
  { id: 17, countryCode: 'AT', countryName: `Autriche`, countryDialCode: `+43` },
  { id: 18, countryCode: 'AZ', countryName: `Azerbaïdjan`, countryDialCode: `+994` },
  { id: 19, countryCode: 'BS', countryName: `Bahamas`, countryDialCode: `+1242` },
  { id: 20, countryCode: 'BH', countryName: `Bahreïn`, countryDialCode: `+973` },
  { id: 21, countryCode: 'BD', countryName: `Bangladesh`, countryDialCode: `+880` },
  { id: 22, countryCode: 'BB', countryName: `Barbade`, countryDialCode: `+1246` },
  { id: 23, countryCode: 'BY', countryName: `Bélarus`, countryDialCode: `+375` },
  { id: 24, countryCode: 'BE', countryName: `Belgique`, countryDialCode: `+32` },
  { id: 25, countryCode: 'BZ', countryName: `Belize`, countryDialCode: `+501` },
  { id: 26, countryCode: 'BJ', countryName: `Bénin`, countryDialCode: `+229` },
  { id: 27, countryCode: 'BM', countryName: `Bermudes`, countryDialCode: `+1441` },
  { id: 28, countryCode: 'BT', countryName: `Bhoutan`, countryDialCode: `+975` },
  { id: 29, countryCode: 'BO', countryName: `Bolivie`, countryDialCode: `+591` },
  { id: 30, countryCode: 'BA', countryName: `Bosnie-Herzégovine`, countryDialCode: `+387` },
  { id: 31, countryCode: 'BW', countryName: `Botswana`, countryDialCode: `+267` },
  { id: 32, countryCode: 'BR', countryName: `Brésil`, countryDialCode: `+55` },
  { id: 33, countryCode: 'BN', countryName: `Brunéi Darussalam`, countryDialCode: `+673` },
  { id: 34, countryCode: 'BG', countryName: `Bulgarie`, countryDialCode: `+359` },
  { id: 35, countryCode: 'BF', countryName: `Burkina Faso`, countryDialCode: `+226` },
  { id: 36, countryCode: 'BI', countryName: `Burundi`, countryDialCode: `+257` },
  { id: 37, countryCode: 'KH', countryName: `Cambodge`, countryDialCode: `+855` },
  { id: 38, countryCode: 'CM', countryName: `Cameroun`, countryDialCode: `+237` },
  { id: 39, countryCode: 'CA', countryName: `Canada`, countryDialCode: `+1` },
  { id: 40, countryCode: 'CV', countryName: `Cap-Vert`, countryDialCode: `+238` },
  //  { id: 41, countryCode: 'EA', countryName: `Ceuta et Melilla`, ``},
  { id: 42, countryCode: 'CL', countryName: `Chili`, countryDialCode: `+56` },
  { id: 43, countryCode: 'CN', countryName: `Chine`, countryDialCode: `+86` },
  { id: 44, countryCode: 'CY', countryName: `Chypre`, countryDialCode: `+357` },
  { id: 45, countryCode: 'CO', countryName: `Colombie`, countryDialCode: `+57` },
  { id: 46, countryCode: 'KM', countryName: `Comores`, countryDialCode: `+269` },
  { id: 47, countryCode: 'CG', countryName: `République du Congo`, countryDialCode: `+242` },
  { id: 48, countryCode: 'KP', countryName: `Corée du Nord`, countryDialCode: `+850` },
  { id: 49, countryCode: 'KR', countryName: `Corée du Sud`, countryDialCode: `+82` },
  { id: 50, countryCode: 'CR', countryName: `Costa Rica`, countryDialCode: `+506` },
  { id: 51, countryCode: 'CI', countryName: `Côte d’Ivoire`, countryDialCode: `+225` },
  { id: 52, countryCode: 'HR', countryName: `Croatie`, countryDialCode: `+385` },
  { id: 53, countryCode: 'CU', countryName: `Cuba`, countryDialCode: `+53` },
  { id: 54, countryCode: 'DK', countryName: `Danemark`, countryDialCode: `+253` },
  { id: 56, countryCode: 'DJ', countryName: `Djibouti`, countryDialCode: `+1809 et +1829 et +1849` },
  { id: 57, countryCode: 'DM', countryName: `Dominique`, countryDialCode: `+1767` },
  { id: 58, countryCode: 'EG', countryName: `Égypte`, countryDialCode: `+20` },
  { id: 59, countryCode: 'SV', countryName: `El Salvador`, countryDialCode: `+503` },
  { id: 60, countryCode: 'AE', countryName: `Émirats arabes unis`, countryDialCode: `+971` },
  { id: 61, countryCode: 'EC', countryName: `Équateur`, countryDialCode: `+593` },
  { id: 62, countryCode: 'ER', countryName: `Érythrée`, countryDialCode: `+291` },
  { id: 63, countryCode: 'ES', countryName: `Espagne`, countryDialCode: `+34` },
  { id: 64, countryCode: 'EE', countryName: `Estonie`, countryDialCode: `+372` },
  { id: 65, countryCode: 'VA', countryName: `État de la Cité du Vatican`, countryDialCode: `+379` },
  { id: 66, countryCode: 'FM', countryName: `États fédérés de Micronésie`, countryDialCode: `+691` },
  { id: 67, countryCode: 'US', countryName: `États-Unis`, countryDialCode: `+1` },
  { id: 68, countryCode: 'ET', countryName: `Éthiopie`, countryDialCode: `+251` },
  { id: 69, countryCode: 'FJ', countryName: `Fidji`, countryDialCode: `+679` },
  { id: 70, countryCode: 'FI', countryName: `Finlande`, countryDialCode: `+358` },
  { id: 71, countryCode: 'FR', countryName: `France`, countryDialCode: `+33` },
  { id: 72, countryCode: 'GA', countryName: `Gabon`, countryDialCode: `+241` },
  { id: 73, countryCode: 'GM', countryName: `Gambie`, countryDialCode: `+220` },
  { id: 74, countryCode: 'GE', countryName: `Géorgie`, countryDialCode: `+995` },
  { id: 75, countryCode: 'GS', countryName: `Géorgie du Sud et les îles Sandwich du Sud`, countryDialCode: `+500` },
  { id: 76, countryCode: 'GH', countryName: `Ghana`, countryDialCode: `+233` },
  { id: 77, countryCode: 'GI', countryName: `Gibraltar`, countryDialCode: `+350` },
  { id: 78, countryCode: 'GR', countryName: `Grèce`, countryDialCode: `+30` },
  { id: 79, countryCode: 'GD', countryName: `Grenade`, countryDialCode: `+1473` },
  { id: 80, countryCode: 'GL', countryName: `Groenland`, countryDialCode: `+299` },
  { id: 81, countryCode: 'GP', countryName: `Guadeloupe`, countryDialCode: `+590` },
  { id: 82, countryCode: 'GU', countryName: `Guam`, countryDialCode: `+1671` },
  { id: 83, countryCode: 'GT', countryName: `Guatemala`, countryDialCode: `+502` },
  { id: 84, countryCode: 'GG', countryName: `Guernesey`, countryDialCode: `+44` },
  { id: 85, countryCode: 'GN', countryName: `Guinée`, countryDialCode: `+224` },
  { id: 86, countryCode: 'GQ', countryName: `Guinée équatoriale`, countryDialCode: `+240` },
  { id: 87, countryCode: 'GW', countryName: `Guinée-Bissau`, countryDialCode: `+245` },
  { id: 88, countryCode: 'GY', countryName: `Guyana`, countryDialCode: `+592` },
  { id: 89, countryCode: 'GF', countryName: `Guyane française`, countryDialCode: `+594` },
  { id: 90, countryCode: 'HT', countryName: `Haïti`, countryDialCode: `+509` },
  { id: 91, countryCode: 'HN', countryName: `Honduras`, countryDialCode: `+504` },
  { id: 92, countryCode: 'HU', countryName: `Hongrie`, countryDialCode: `+36` },
  { id: 93, countryCode: 'BV', countryName: `Île Bouvet`, countryDialCode: `+47` },
  { id: 94, countryCode: 'CX', countryName: `Île Christmas`, countryDialCode: `+672` },
  { id: 96, countryCode: 'AC', countryName: `Île de l'Ascension`, countryDialCode: `+290` },
  { id: 97, countryCode: 'IM', countryName: `Île de Man`, countryDialCode: `+44` },
  { id: 98, countryCode: 'NF', countryName: `Île Norfolk`, countryDialCode: `+6723` },
  { id: 99, countryCode: 'AX', countryName: `Îles Åland`, countryDialCode: `+358` },
  { id: 100, countryCode: 'KY', countryName: `Îles Caïmans`, countryDialCode: `+1345` },
  { id: 101, countryCode: 'IC', countryName: `Îles Canaries`, countryDialCode: `+1345` },
  { id: 102, countryCode: 'CC', countryName: `Îles Cocos - Keeling`, countryDialCode: `+672` },
  { id: 103, countryCode: 'CK', countryName: `Îles Cook`, countryDialCode: `+ 682` },
  { id: 104, countryCode: 'FO', countryName: `Îles Féroé`, countryDialCode: `+298` },
  { id: 105, countryCode: 'HM', countryName: `Îles Heard et MacDonald`, countryDialCode: `+672` },
  { id: 106, countryCode: 'FK', countryName: `Îles Malouines`, countryDialCode: `+500` },
  { id: 107, countryCode: 'MP', countryName: `Îles Mariannes du Nord`, countryDialCode: `+1670` },
  { id: 108, countryCode: 'MH', countryName: `Îles Marshall`, countryDialCode: `+692` },
  { id: 110, countryCode: 'SB', countryName: `Îles Salomon`, countryDialCode: `+677` },
  { id: 111, countryCode: 'TC', countryName: `Îles Turks et Caïques`, countryDialCode: `+1649` },
  { id: 112, countryCode: 'VG', countryName: `Îles Vierges britanniques`, countryDialCode: `+1284` },
  { id: 113, countryCode: 'VI', countryName: `Îles Vierges des États-Unis`, countryDialCode: `+1340` },
  { id: 114, countryCode: 'IN', countryName: `Inde`, countryDialCode: `+91` },
  { id: 115, countryCode: 'ID', countryName: `Indonésie`, countryDialCode: `+62` },
  { id: 116, countryCode: 'IQ', countryName: `Irak`, countryDialCode: `+964` },
  { id: 117, countryCode: 'IR', countryName: `Iran`, countryDialCode: `+98` },
  { id: 118, countryCode: 'IE', countryName: `Irlande`, countryDialCode: `+353` },
  { id: 119, countryCode: 'IS', countryName: `Islande`, countryDialCode: `+354` },
  { id: 120, countryCode: 'Pa', countryName: `Palestine`, countryDialCode: `+970` },
  { id: 121, countryCode: 'IT', countryName: `Italie`, countryDialCode: `+39` },
  { id: 122, countryCode: 'JM', countryName: `Jamaïque`, countryDialCode: `1876` },
  { id: 123, countryCode: 'JP', countryName: `Japon`, countryDialCode: `+81` },
  { id: 124, countryCode: 'JE', countryName: `Jersey`, countryDialCode: `+44` },
  { id: 125, countryCode: 'JO', countryName: `Jordanie`, countryDialCode: `+962` },
  { id: 126, countryCode: 'KZ', countryName: `Kazakhstan`, countryDialCode: `+7` },
  { id: 127, countryCode: 'KE', countryName: `Kenya`, countryDialCode: `+254` },
  { id: 128, countryCode: 'KG', countryName: `Kirghizistan`, countryDialCode: `+996` },
  { id: 129, countryCode: 'KI', countryName: `Kiribati`, countryDialCode: `+686` },
  { id: 130, countryCode: 'KW', countryName: `Koweït`, countryDialCode: `+965` },
  { id: 131, countryCode: 'LA', countryName: `Laos`, countryDialCode: `+856` },
  { id: 132, countryCode: 'LS', countryName: `Lesotho`, countryDialCode: `+266` },
  { id: 134, countryCode: 'LV', countryName: `Lettonie`, countryDialCode: `+371` },
  { id: 135, countryCode: 'LB', countryName: `Liban`, countryDialCode: `+961` },
  { id: 136, countryCode: 'LR', countryName: `Libéria`, countryDialCode: `+231` },
  { id: 137, countryCode: 'LY', countryName: `Libye`, countryDialCode: `+218` },
  { id: 138, countryCode: 'LI', countryName: `Liechtenstein`, countryDialCode: `+423` },
  { id: 139, countryCode: 'LT', countryName: `Lituanie`, countryDialCode: `+370` },
  { id: 140, countryCode: 'LU', countryName: `Luxembourg`, countryDialCode: `+352` },
  { id: 141, countryCode: 'MK', countryName: `Macédoine`, countryDialCode: `+389` },
  { id: 142, countryCode: 'MG', countryName: `Madagascar`, countryDialCode: `+261` },
  { id: 143, countryCode: 'MY', countryName: `Malaisie`, countryDialCode: `+60` },
  { id: 144, countryCode: 'MW', countryName: `Malawi`, countryDialCode: `+265` },
  { id: 145, countryCode: 'MV', countryName: `Maldives`, countryDialCode: `+960` },
  { id: 146, countryCode: 'ML', countryName: `Mali`, countryDialCode: `+223` },
  { id: 147, countryCode: 'MT', countryName: `Malte`, countryDialCode: `+356` },
  { id: 148, countryCode: 'MA', countryName: `Maroc`, countryDialCode: `+212` },
  { id: 149, countryCode: 'MQ', countryName: `Martinique`, countryDialCode: `+596` },
  { id: 150, countryCode: 'MU', countryName: `Maurice`, countryDialCode: `+230` },
  { id: 151, countryCode: 'MR', countryName: `Mauritanie`, countryDialCode: `+222` },
  { id: 151, countryCode: 'YT', countryName: `Mayotte`, countryDialCode: `+262` },
  { id: 152, countryCode: 'MX', countryName: `Mexique`, countryDialCode: `+52` },
  { id: 153, countryCode: 'MD', countryName: `Moldavie`, countryDialCode: `+373` },
  { id: 154, countryCode: 'MC', countryName: `Monaco`, countryDialCode: `+377` },
  { id: 155, countryCode: 'MN', countryName: `Mongolie`, countryDialCode: `+976` },
  { id: 156, countryCode: 'ME', countryName: `Monténégro`, countryDialCode: `+382` },
  { id: 157, countryCode: 'MS', countryName: `Montserrat`, countryDialCode: `+1664` },
  { id: 158, countryCode: 'MZ', countryName: `Mozambique`, countryDialCode: `+258` },
  { id: 159, countryCode: 'MM', countryName: `Myanmar`, countryDialCode: `+95` },
  { id: 160, countryCode: 'NA', countryName: `Namibie`, countryDialCode: `+264` },
  { id: 161, countryCode: 'NR', countryName: `Nauru`, countryDialCode: `+674` },
  { id: 162, countryCode: 'NP', countryName: `Népal`, countryDialCode: `+977` },
  { id: 163, countryCode: 'NI', countryName: `Nicaragua`, countryDialCode: `+505` },
  { id: 164, countryCode: 'NE', countryName: `Niger`, countryDialCode: `+227` },
  { id: 165, countryCode: 'NG', countryName: `Nigéria`, countryDialCode: `+234` },
  { id: 166, countryCode: 'NU', countryName: `Niue`, countryDialCode: `+683` },
  { id: 167, countryCode: 'NO', countryName: `Norvège`, countryDialCode: `+47` },
  { id: 168, countryCode: 'NC', countryName: `Nouvelle-Calédonie`, countryDialCode: `+687` },
  { id: 169, countryCode: 'NZ', countryName: `Nouvelle-Zélande`, countryDialCode: `+64` },
  { id: 170, countryCode: 'OM', countryName: `Oman`, countryDialCode: `+968` },
  { id: 171, countryCode: 'UG', countryName: `Ouganda`, countryDialCode: `+256` },
  { id: 172, countryCode: 'UZ', countryName: `Ouzbékistan`, countryDialCode: `+998` },
  { id: 173, countryCode: 'PK', countryName: `Pakistan`, countryDialCode: `+92` },
  { id: 174, countryCode: 'PW', countryName: `Palaos`, countryDialCode: `+680` },
  { id: 175, countryCode: 'PA', countryName: `Panama`, countryDialCode: `+507` },
  { id: 176, countryCode: 'PG', countryName: `Papouasie-Nouvelle-Guinée`, countryDialCode: `+675` },
  { id: 177, countryCode: 'PY', countryName: `Paraguay`, countryDialCode: `+595` },
  { id: 178, countryCode: 'NL', countryName: `Pays-Bas`, countryDialCode: `+31` },
  { id: 179, countryCode: 'PE', countryName: `Pérou`, countryDialCode: `+51` },
  { id: 180, countryCode: 'PH', countryName: `Philippines`, countryDialCode: `+63` },
  { id: 181, countryCode: 'PN', countryName: `Pitcairn`, countryDialCode: `+64` },
  { id: 182, countryCode: 'PL', countryName: `Pologne`, countryDialCode: `+48` },
  { id: 183, countryCode: 'PF', countryName: `Polynésie française`, countryDialCode: `+689` },
  { id: 184, countryCode: 'PR', countryName: `Porto Rico`, countryDialCode: `+1787 et +1939` },
  { id: 185, countryCode: 'PT', countryName: `Portugal`, countryDialCode: `+351` },
  { id: 186, countryCode: 'QA', countryName: `Qatar`, countryDialCode: `+974` },
  { id: 187, countryCode: 'HK', countryName: `R.A.S. chinoise de Hong Kong`, countryDialCode: `+852` },
  { id: 188, countryCode: 'MO', countryName: `R.A.S. chinoise de Macao`, countryDialCode: `+853` },
  { id: 190, countryCode: 'CF', countryName: `République centrafricaine`, countryDialCode: `+236` },
  { id: 191, countryCode: 'CD', countryName: `République démocratique du Congo`, countryDialCode: `+243` },
  { id: 192, countryCode: 'DO', countryName: `République dominicaine`, countryDialCode: `+1809` },
  { id: 193, countryCode: 'CZ', countryName: `République tchèque`, countryDialCode: `+420` },
  { id: 194, countryCode: 'RE', countryName: `Réunion`, countryDialCode: `+262` },
  { id: 195, countryCode: 'RO', countryName: `Roumanie`, countryDialCode: `+40` },
  { id: 196, countryCode: 'GB', countryName: `Royaume-Uni`, countryDialCode: `+44` },
  { id: 197, countryCode: 'RU', countryName: `Russie`, countryDialCode: `+7` },
  { id: 199, countryCode: 'RW', countryName: `Rwanda`, countryDialCode: `+250` },
  { id: 200, countryCode: 'EH', countryName: `Sahara occidental`, countryDialCode: `+212` },
  { id: 201, countryCode: 'BL', countryName: `Saint-Barthélémy`, countryDialCode: `+590` },
  { id: 203, countryCode: 'SM', countryName: `Saint-Marin`, countryDialCode: `+378` },
  { id: 204, countryCode: 'MF', countryName: `Saint-Martin`, countryDialCode: `+590` },
  { id: 205, countryCode: 'PM', countryName: `Saint-Pierre-et-Miquelon`, countryDialCode: `+508` },
  { id: 206, countryCode: 'VC', countryName: `Saint-Vincent-et-les Grenadines`, countryDialCode: `+1784` },
  { id: 207, countryCode: 'SH', countryName: `Sainte-Hélène`, countryDialCode: `+290` },
  { id: 208, countryCode: 'LC', countryName: `Sainte-Lucie`, countryDialCode: `+1758` },
  { id: 209, countryCode: 'WS', countryName: `Samoa`, countryDialCode: `+685` },
  { id: 210, countryCode: 'AS', countryName: `Samoa américaines`, countryDialCode: `+1684` },
  { id: 211, countryCode: 'ST', countryName: `Sao Tomé-et-Principe`, countryDialCode: `+239` },
  { id: 212, countryCode: 'SN', countryName: `Sénégal`, countryDialCode: `+221` },
  { id: 213, countryCode: 'RS', countryName: `Serbie`, countryDialCode: `+381` },
  { id: 214, countryCode: 'CS', countryName: `Serbie-et-Monténégro`, countryDialCode: `+382` },
  { id: 215, countryCode: 'SC', countryName: `Seychelles`, countryDialCode: `+248` },
  { id: 216, countryCode: 'SL', countryName: `Sierra Leone`, countryDialCode: `+232` },
  { id: 217, countryCode: 'SG', countryName: `Singapour`, countryDialCode: `+65` },
  { id: 218, countryCode: 'SK', countryName: `Slovaquie`, countryDialCode: `+421` },
  { id: 219, countryCode: 'SI', countryName: `Slovénie`, countryDialCode: `+386` },
  { id: 220, countryCode: 'SO', countryName: `Somalie`, countryDialCode: `+252` },
  { id: 221, countryCode: 'SD', countryName: `Soudan`, countryDialCode: `+249` },
  { id: 222, countryCode: 'LK', countryName: `Sri Lanka`, countryDialCode: `+94` },
  { id: 223, countryCode: 'SE', countryName: `Suède`, countryDialCode: `+46` },
  { id: 224, countryCode: 'CH', countryName: `Suisse`, countryDialCode: `+41` },
  { id: 225, countryCode: 'SR', countryName: `Suriname`, countryDialCode: `+597` },
  { id: 226, countryCode: 'SJ', countryName: `Svalbard et Île Jan Mayen`, countryDialCode: `+47` },
  { id: 227, countryCode: 'SZ', countryName: `Swaziland`, countryDialCode: `+268` },
  { id: 228, countryCode: 'SY', countryName: `Syrie`, countryDialCode: `+963` },
  { id: 229, countryCode: 'TJ', countryName: `Tadjikistan`, countryDialCode: `+992` },
  { id: 230, countryCode: 'TW', countryName: `Taïwan`, countryDialCode: `+886` },
  { id: 231, countryCode: 'TZ', countryName: `Tanzanie`, countryDialCode: `+255` },
  { id: 232, countryCode: 'TD', countryName: `Tchad`, countryDialCode: `+235` },
  { id: 233, countryCode: 'TF', countryName: `Terres australes françaises`, countryDialCode: `+262` },
  { id: 234, countryCode: 'IO', countryName: `Territoire britannique de l'océan Indien`, countryDialCode: `+246` },
  { id: 235, countryCode: 'PS', countryName: `Territoire palestinien`, countryDialCode: `+672` },
  { id: 236, countryCode: 'TH', countryName: `Thaïlande`, countryDialCode: `+66` },
  { id: 237, countryCode: 'TL', countryName: `Timor oriental`, countryDialCode: `+670` },
  { id: 238, countryCode: 'TG', countryName: `Togo`, countryDialCode: `+228` },
  { id: 239, countryCode: 'TK', countryName: `Tokelau`, countryDialCode: `+690` },
  { id: 240, countryCode: 'TO', countryName: `Tonga`, countryDialCode: `+676` },
  { id: 241, countryCode: 'TT', countryName: `Trinité-et-Tobago`, countryDialCode: `+1868` },
  { id: 242, countryCode: 'TA', countryName: `Tristan da Cunha`, countryDialCode: `+290` },
  { id: 243, countryCode: 'TN', countryName: `Tunisie`, countryDialCode: `+216` },
  { id: 244, countryCode: 'TM', countryName: `Turkménistan`, countryDialCode: `+993` },
  { id: 245, countryCode: 'TR', countryName: `Turquie`, countryDialCode: `+90` },
  { id: 246, countryCode: 'TV', countryName: `Tuvalu`, countryDialCode: `+688` },
  { id: 247, countryCode: 'UA', countryName: `Ukraine`, countryDialCode: `+380` },
  { id: 249, countryCode: 'UY', countryName: `Uruguay`, countryDialCode: `+598` },
  { id: 250, countryCode: 'VU', countryName: `Vanuatu`, countryDialCode: `+678` },
  { id: 251, countryCode: 'VE', countryName: `Venezuela`, countryDialCode: `+58` },
  { id: 252, countryCode: 'VN', countryName: `Viêt Nam`, countryDialCode: `+84` },
  { id: 253, countryCode: 'WF', countryName: `Wallis-et-Futuna`, countryDialCode: `+681` },
  { id: 254, countryCode: 'YE', countryName: `Yémen`, countryDialCode: `+967` },
  { id: 255, countryCode: 'ZM', countryName: `Zambie`, countryDialCode: `+260` },
  { id: 256, countryCode: 'ZW', countryName: `Zimbabwe`, countryDialCode: `+263` }
];
